/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'oliver' at '23.03.16 12:35' with Gradle 2.11
 *
 * @author oliver, @date 23.03.16 12:35
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
