ALTER TABLE "CONTENT_FILEDERIVATES" ADD PARENT_ID VARCHAR2(32) DEFAULT NULL;
CREATE INDEX T38_PARENT_ID ON CONTENT_FILEDERIVATES (parent_id);
ALTER TABLE "EXTENSIONDATA" ADD BINARYVALUE_SHA512 VARCHAR2(128) DEFAULT NULL;
CREATE INDEX T28_BINARYVALUE_SHA512 ON EXTENSIONDATA (binaryvalue_sha512);