ALTER TABLE "CONTENT_FILEDERIVATES" ADD "PARENT_ID" varchar(32) WITH DEFAULT NULL;
CREATE INDEX T38_PARENT_ID ON CONTENT_FILEDERIVATES (parent_id);
ALTER TABLE "EXTENSIONDATA" ADD "BINARYVALUE_SHA512" varchar(128) WITH DEFAULT NULL;
CREATE INDEX T28_BINARYVALUE_SHA512 ON EXTENSIONDATA (binaryvalue_sha512);