ALTER TABLE content_filederivates ADD "PARENT_ID" VARCHAR(32) NULL;
CREATE INDEX T38_PARENT_ID ON content_filederivates (PARENT_ID);
ALTER TABLE extensiondata ADD "BINARYVALUE_SHA512" VARCHAR(128) NULL;
CREATE INDEX T28_BINARYVALUE_SHA512 ON extensiondata (BINARYVALUE_SHA512);